### ISSUE TITLE
Open With raises error on windows 7

### ISSUE THREAD

**Issue by andhoiras** [agateau/OpenWith#2]
Command 'OpenWith' raised error.
```
Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 270, in _run_in_thread
  File "C:\Users\ARAS\AppData\Roaming\fman\Plugins\Third-party\OpenWith\openwith\__init__.py", line 25, in __call__
    stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL, env=env)
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 955, in _execute_child
NotADirectoryError: [WinError 267] The directory name is invalid
```

**Comment by agateau** [comment]
The plugin is complaining about an invalid directory, did you start it from a special place? How can I reproduce that bug?

**Comment by andhoiras** [comment]
I started the fman application on windows 7 office PC with multiple users. I am not the admin of the computer. Other plugins work fine with fman.

**Comment by agateau** [comment]
I just pushed a fix, should be good now. Please reopen if it is not the case.
